### ISSUE TITLE
Values of CF and Dr

### ISSUE THREAD

**Issue by antonioricciardi16** [SNU-LIST/chi-separation#1]
Hello. I understand that the value of the central frequency (CF = 123e6 Hz) is given by the gyromagnetic ratio 42.577e6 Hz/T times 2.9T, although the comments state this should be the value at 3T. At 3T, it would be 127e6 Hz. What value should I use on a 3T system? Thank you.

**Comment by LISTatSNU** [comment]
The "3T" in the comments just means a simple convention for a commercial 3T scanner. CF can be the exact value such as CF at 2.9 T.
